
const wordlist = [
    { id: "nA001", type: "n", word: "Appel", meaning: "apple" },
    { id: "nA002", type: "n", word: "Arm", meaning: "arm" },

    { id: "nÅ001", type: "n", word: "Ård", meaning: "earth" },
    { id: "nÅ002", type: "n", word: "Årdiscund", meaning: "geology" },
    { id: "nÅ003", type: "n", word: "Årdwyrldiscund", meaning: "geography" },

    { id: "nB001", type: "n", word: "Been", meaning: "bone, leg" },
    { id: "nB002", type: "n", word: "Bjår", meaning: "gesture, movement" },
    { id: "nB003", type: "n", word: "Bloft", meaning: "promise" },
    { id: "nB004", type: "n", word: "Blůd", meaning: "blood" },
    { id: "nB005", type: "n", word: "Blům", meaning: "flower" },
    { id: "nB006", type: "n", word: "Boom", meaning: "tree" },
    { id: "nB007", type: "n", word: "Brood", meaning: "bread" },
    { id: "nB008", type: "n", word: "Bryn", meaning: "brain, mind" },
    { id: "nB009", type: "n", word: "Burgh", meaning: "borrow, fortified settlement" },
    { id: "nB010", type: "n", word: "Bůck", meaning: "book" },
    { id: "nB011", type: "n", word: "Byrgh", meaning: "mountain" },

    { id: "nC001", type: "n", word: "Cac", meaning: "poop" },
    { id: "nC002", type: "n", word: "Cack", meaning: "shit" },
    { id: "nC003", type: "n", word: "Cant", meaning: "side, edge" },
    { id: "nC004", type: "n", word: "Cafirn", meaning: "cave, grotte, large submerged opening" },
    { id: "nC005", type: "n", word: "Cås", meaning: "cheese" },
    { id: "nC006", type: "n", word: "Cind", meaning: "child" },
    { id: "nC007", type: "n", word: "Cir", meaning: "time, opportunity, chance" },
    { id: "nC008", type: "n", word: "Clur", meaning: "colour" },
    { id: "nC009", type: "n", word: "Craght", meaning: "power, energy" },

    { id: "nD001", type: "n", word: "Dagh", meaning: "day" },
    { id: "nD002", type: "n", word: "Denck", meaning: "thought" },
    { id: "nD003", type: "n", word: "Din", meaning: "thing" },
    { id: "nD004", type: "n", word: "Doghter", meaning: "daughter" },

    { id: "nE001", type: "n", word: "End", meaning: "end" },
	{ id: "nE002", type: "n", word: "Emmer", meaning: "bowl" },

    { id: "nF001", type: "n", word: "Fan", meaning: "joke" },
    { id: "nF002", type: "n", word: "Farcen", meaning: "pig" },
    { id: "nF003", type: "n", word: "Fåder", meaning: "father" },
    { id: "nF004", type: "n", word: "Finjer", meaning: "finger, digit" },
    { id: "nF005", type: "n", word: "Fisj", meaning: "fish" },
    { id: "nF006", type: "n", word: "Frubrigh", meaning: "volcano" },
    { id: "nF007", type: "n", word: "Frubriglas", meaning: "volcano glass, dark glass, obsidian glass" },
    { id: "nF008", type: "n", word: "Fjanis", meaning: "jail, prison" },
    { id: "nF009", type: "n", word: "Fjůln", meaning: "feeling" },
    { id: "nF010", type: "n", word: "Fjůr", meaning: "fire" },
    { id: "nF011", type: "n", word: "Foil", meaning: "bird" },
    { id: "nF012", type: "n", word: "Fgrål", meaning: "story" },
    { id: "nF013", type: "n", word: "fgrålcen", meaning: "small talk" },
    { id: "nF014", type: "n", word: "Fro", meaning: "woman" },
    { id: "nF015", type: "n", word: "Frooc", meaning: "girl" },
    { id: "nF016", type: "n", word: "Frught", meaning: "fruit" },
    { id: "nF017", type: "n", word: "Fůt", meaning: "foot" },
    { id: "nF018", type: "n", word: "Fůtganjer", meaning: "pedestrian" },
    { id: "nF019", type: "n", word: "Fyl", meaning: "skin" },
    { id: "nF020", type: "n", word: "Fylighyd", meaning: "safety" },
	
    { id: "nG001", type: "n", word: "Glimlagh", meaning: "happiness" },
    { id: "nG002", type: "n", word: "God", meaning: "god" },
    { id: "nG003", type: "n", word: "Glas", meaning: "glass" },
    { id: "nG004", type: "n", word: "Gras", meaning: "grass" },

    { id: "nH001", type: "n", word: "Hand", meaning: "hand" },
    { id: "nH002", type: "n", word: "Håfin", meaning: "harbour" },
    { id: "nH003", type: "n", word: "Heem", meaning: "home" },
    { id: "nH004", type: "n", word: "Hjoorsåmhyd", meaning: "obedience" },
    { id: "nH005", type: "n", word: "Hjůs", meaning: "house" },
    { id: "nH006", type: "n", word: "Hjůsnooi", meaning: "window" },
    { id: "nH007", type: "n", word: "Hond", meaning: "dog" },
    { id: "nH008", type: "n", word: "Hooft", meaning: "head" },
    { id: "nH009", type: "n", word: "Hors", meaning: "horse" },
    { id: "nH010", type: "n", word: "Hyrt", meaning: "heart" },

    { id: "nJ001", type: "n", word: "Jår", meaning: "year" },
    { id: "nJ002", type: "n", word: "juldjen", meaning: "guilder" },
    { id: "nJ003", type: "n", word: "Jůr", meaning: "hour" },
    { id: "nJ004", type: "n", word: "Jyld", meaning: "money" },

    { id: "nL001", type: "n", word: "Lefen", meaning: "life" },
    { id: "nL002", type: "n", word: "Letter", meaning: "letter" },
    { id: "nL003", type: "n", word: "Ljuck", meaning: "luck" },
    { id: "nL004", type: "n", word: "Lust", meaning: "desire, urge" },

    { id: "nM001", type: "n", word: "Man", meaning: "man" },
    { id: "nM002", type: "n", word: "Manc", meaning: "boy" },
    { id: "nM003", type: "n", word: "Mand", meaning: "month, season" },
    { id: "nM004", type: "n", word: "Masjimum", meaning: "maximum" },
    { id: "nM005", type: "n", word: "Menc", meaning: "person" },
    { id: "nM006", type: "n", word: "Mind", meaning: "middle, centre" },
    { id: "nM007", type: "n", word: "Minimum", meaning: "minimum" },
    { id: "nM008", type: "n", word: "Misnemin", meaning: "mistake" },
    { id: "nM009", type: "n", word: "Mjůs", meaning: "mouse" },
    { id: "nM010", type: "n", word: "Můder", meaning: "mother" },

    { id: "nN001", type: "n", word: "Naght", meaning: "night" },
    { id: "nN002", type: "n", word: "Nakjůr", meaning: "nature" },
    { id: "nN003", type: "n", word: "Neus", meaning: "nose" },
    { id: "nN004", type: "n", word: "Njietin", meaning: "fun" },
    { id: "nN005", type: "n", word: "Njietplyc", meaning: "third place, area away from work and family" },
    { id: "nN006", type: "n", word: "Njůt", meaning: "minute" },
    { id: "nN007", type: "n", word: "Nåm", meaning: "name" },

    { id: "nO001", type: "n", word: "Oghend", meaning: "morning" },
    { id: "nO002", type: "n", word: "Onnergůd", meaning: "underwear" },
    { id: "nO003", type: "n", word: "Ooi", meaning: "eye" },

    { id: "nP001", type: "n", word: "Pård", meaning: "vehicle" },
    { id: "nP002", type: "n", word: "Plyc", meaning: "place, spot" },
    { id: "nP003", type: "n", word: "Prerstir", meaning: "performance" },
    { id: "nP004", type: "n", word: "Prsoonlighyd", meaning: "personality" },

    { id: "nR001", type: "n", word: "Rodwyn", meaning: "red wine" },
    { id: "nR002", type: "n", word: "Rui", meaning: "back" },
    { id: "nR003", type: "n", word: "Ryght", meaning: "right" },

    { id: "nS001", type: "n", word: "Se", meaning: "sea" },
    { id: "nS002", type: "n", word: "Suåret", meaning: "cigarette" },
    { id: "nS003", type: "n", word: "Sjenck", meaning: "gift" },
    { id: "nS004", type: "n", word: "Sjip", meaning: "ship" },
    { id: "nS005", type: "n", word: "Sjol", meaning: "school" },
    { id: "nS006", type: "n", word: "Sjlaght", meaning: "gender" },
    { id: "nS007", type: "n", word: "Sjyrm", meaning: "screen, protection" },
    { id: "nS008", type: "n", word: "Sleutel", meaning: "key" },
    { id: "nS009", type: "n", word: "Sorgh", meaning: "care, worry" },
    { id: "nS010", type: "n", word: "Stuck", meaning: "piece" },
    { id: "nS011", type: "n", word: "Stylin", meaning: "system" },

    { id: "nT001", type: "n", word: "Tål", meaning: "language" },
    { id: "nT002", type: "n", word: "Tålscund", meaning: "linguistics" },
    { id: "nT003", type: "n", word: "Tand", meaning: "tooth" },
    { id: "nT004", type: "n", word: "Ton", meaning: "tongue" },
    { id: "nT005", type: "n", word: "Tryck", meaning: "journey, visit" },
    { id: "nT006", type: "n", word: "Tyd", meaning: "time" },

    { id: "nU001", type: "n", word: "Unifyrste", meaning: "university" },
    { id: "nU002", type: "n", word: "Uinblick", meaning: "moment" },

    { id: "nŮ001", type: "n", word: "Ůf", meaning: "practice" },

    { id: "nW001", type: "n", word: "Wåter", meaning: "water" },
    { id: "nW002", type: "n", word: "Wesen", meaning: "being" },
    { id: "nW003", type: "n", word: "Word", meaning: "word" },
    { id: "nW004", type: "n", word: "Wygh", meaning: "way, manner, path, away" },
    { id: "nW005", type: "n", word: "Wyn", meaning: "wine" },
    { id: "nW006", type: "n", word: "Vyrld", meaning: "world" },
    { id: "nW007", type: "n", word: "Woordenbůck", meaning: "dictionary, wordbook" },

    { id: "nY001", type: "n", word: "Yngel", meaning: "angel, loved one" },
  { id: "nY002", type: "n", word: "Ys", meaning: "ice" },
  
  { id: "nÅ001", type: "n", word: "Åp", meaning: "ape" },
{ id: "nÅ002", type: "n", word: "Åpsj", meaning: "monkey" },
{ id: "nC010", type: "n", word: "Cåbjůs", meaning: "kitchen" },
{ id: "nE003", type: "n", word: "Ecoorn", meaning: "squirrel" },
{ id: "nI001", type: "n", word: "Indruck", meaning: "pressue" },
{ id: "nJ005", type: "n", word: "Jyt", meaning: "goat" },
{ id: "nN008", type: "n", word: "Nåjel", meaning: "nail" },
{ id: "nO004", type: "n", word: "Ordin", meaning: "order" },
{ id: "nO005", type: "n", word: "Oorsåck", meaning: "cause" },
{ id: "nQ001", type: "n", word: "Quast", meaning: "brush" },
{ id: "nD005", type: "n", word: "Disj", meaning: "table" },
{ id: "nS012", type: "n", word: "Sjů", meaning: "shoe" },
{ id: "nF021", type: "n", word: "Forstylin", meaning: "idea" },
{ id: "nA003", type: "n", word: "Aripennon", meaning: "extremity" },
{ id: "nK001", type: "n", word: "Kjost", meaning: "cost" },

{ id:"vA001", word:"acepten", ipa:"[ʔɐˈtɕɛp.ʔn̩]", meaning:"accept", type:"v" },
{ id:"vÅ001", word:"ånfården", ipa:"[ˈʔɒ̃ɱ.fɒ.ɖɳ̩]", meaning:"address", type:"v" },
{ id:"vB001", word:"bhoden", ipa:"[ˈbɦo̤ʊ̤.dn̩]", meaning:"preserve, save", type:"v" },
{ id:"vC001", word:"cacen", ipa:"[ˈkʰɐ.tɕɲ̩]", meaning:"poop", type:"v" },
{ id:"vC002", word:"cacken", ipa:"[ˈkʰɐ.ʔŋ̩]", meaning:"shit", type:"v" },
{ id:"vD001", word:"dencen", ipa:"[ˈdɛ̃ɲ.tɕɲ̩]", meaning:"think", type:"v" },
{ id:"vS001", word:"syn", ipa:"[ˈsãŋ]", meaning:"be", type:"v" },
{ id:"vC003", word:"comen", ipa:"[ˈkʰõʊ̃.mŋ̩]", meaning:"come", type:"v" },
{ id:"vB002", word:"bhoorn", ipa:"[ˈbɦõ̤ʊ̤̃ɳ]", meaning:"belong", type:"v" },
{ id:"vB003", word:"boon", ipa:"[ˈbõʊ̃ŋ]", meaning:"build", type:"v" },
{ id:"vF001", word:"fůln", ipa:"[ˈfɯɔn]", meaning:"feel", type:"v" },
{ id:"vG001", word:"gån", ipa:"[ˈɰɒ̃ŋ]", meaning:"go", type:"v" },
{ id:"vG002", word:"gråln", ipa:"[ˈɹʷˠɒɔn]", meaning:"repeat", type:"v" },
{ id:"vH001", word:"hebben", ipa:"[ˈɦɛ̤.bm̩]", meaning:"have", type:"v" },
{ id:"vH002", word:"hoorn", ipa:"[ˈɦõ̤ʊ̤̃ɳ]", meaning:"hear", type:"v" },


{ id:"aA001", type:"a", word:"Anmoinligh", ipa:"[ʔɐ̃ŋˈmɔ̃ɪ̃ɲ.ʎɪj]", meaning:"impossible" },
{ id:"aA002", type:"a", word:"Anryght", ipa:"[ʔɐ̃ɳˈɻaɪʔ]", meaning:"incorrect, wrong" },
{ id:"aB001", type:"a", word:"Bloshandåfigh", ipa:"[ˈblɔsˌɦɐ̤̃n.dɒ.fɪj]", meaning:"cute" },
{ id:"aQ001", type:"a", word:"Quick", ipa:"[kfɪk]", meaning:"smart" },
{ id:"aC001", type:"a", word:"Clyn", ipa:"[ˈkl̥ãŋ]", meaning:"small" },

];

