const wordlist = [
    { id: "nA001", type: "n", word: "Appel", ipa: "[ˈʔɐ.pɔ]", meaning: "apple" }, 
    { id: "nA002", type: "n", word: "Arm", ipa: "[ˈʔɒˑm]", meaning: "arm" }, 
 
    { id: "nÅ001", type: "n", word: "Ård", ipa: "[ˈʔɒɘʔ]", meaning: "earth" }, 
    { id: "nÅ002", type: "n", word: "Årdiscund", ipa: "[ˈʔɒ.ɖɪɕ.tɕʏ̃ˑʔ]", meaning: "geology" }, 
    { id: "nÅ003", type: "n", word: "Årdwyrldiscund", ipa: "[ˈʔɒɖˌvaɭ.ɖɪɕ.tɕʏ̃ˑʔ]", meaning: "geography" }, 
 
    { id: "nB001", type: "n", word: "Been", ipa: "[ˈbẽɪ̃ɲ]", meaning: "bone, leg" }, 
    { id: "nB002", type: "n", word: "Bjår", ipa: "[ˈbjɒɘ]", meaning: "gesture, movement" }, 
    { id: "nB003", type: "n", word: "Bloft", ipa: "[ˈblɔf(t)]", meaning: "promise" }, 
    { id: "nB004", type: "n", word: "Blůd", ipa: "[ˈblɯʔ]", meaning: "blood" }, 
    { id: "nB005", type: "n", word: "Blům", ipa: "[ˈblɯ̃m]", meaning: "flower" }, 
    { id: "nB006", type: "n", word: "Boom", ipa: "[ˈbõʊ̃m]", meaning: "tree" }, 
    { id: "nB007", type: "n", word: "Brood", ipa: "[bɻoʊʔ]", meaning: "bread" }, 
    { id: "nB008", type: "n", word: "Bryn", ipa: "[ˈbɻãŋ]", meaning: "brain, mind" }, 
    { id: "nB009", type: "n", word: "Burgh", ipa: "[ˈbʏ.ɻʏɥ]", meaning: "borrow, fortified settlement" }, 
    { id: "nB010", type: "n", word: "Bůck", ipa: "[ˈbɯk]", meaning: "book" }, 
    { id: "nB011", type: "n", word: "Byrgh", ipa: "[ˈba.ɻeɪ]", meaning: "mountain" }, 
 
    { id: "nC001", type: "n", word: "Cac", ipa: "[ˈkʰɐtɕ]", meaning: "poop" }, 
    { id: "nC002", type: "n", word: "Cack", ipa: "[ˈkʰɐk]", meaning: "shit" }, 
    { id: "nC003", type: "n", word: "Cant", ipa: "[ˈkʰɒ̃ˑʔ]", meaning: "side, edge" }, 
    { id: "nC004", type: "n", word: "Cafirn", ipa: "[ˈkʰɐ.vɪɳ]", meaning: "cave, grotte, large submerged opening" }, 
    { id: "nC005", type: "n", word: "Cås", ipa: "[ˈkʰɒs]", meaning: "cheese" }, 
    { id: "nC006", type: "n", word: "Cind", ipa: "[ˈtɕɪ̃ˑʔ]", meaning: "child" }, 
    { id: "nC007", type: "n", word: "Cir", ipa: "[ˈtɕɪɘ]", meaning: "time, opportunity, chance" }, 
    { id: "nC008", type: "n", word: "Clur", ipa: "[ˈkl̥ʏɘ]", meaning: "colour" }, 
    { id: "nC009", type: "n", word: "Craght", ipa: "[ˈkʰɻ̥ɐɘʔ]", meaning: "power, energy" }, 
 
    { id: "nD001", type: "n", word: "Dagh", ipa: "[ˈdɐɘ]", meaning: "day" }, 
    { id: "nD002", type: "n", word: "Denck", ipa: "[dẽɪ̃k]", meaning: "thought" }, 
    { id: "nD003", type: "n", word: "Din", ipa: "[ˈdɪ̃ɲ]", meaning: "thing" }, 
    { id: "nD004", type: "n", word: "Doghter", ipa: "[ˈdoʊ.ʈɘ]", meaning: "daughter" }, 
 
    { id: "nE001", type: "n", word: "End", ipa: "[ˈʔẽɪ̃ʔ]", meaning: "end" }, 
    { id: "nE002", type: "n", word: "Emmer", ipa: "[ˈʔɛ̃.mɘ]", meaning: "bowl" }, 
 
    { id: "nF001", type: "n", word: "Fan", ipa: "[ˈfɐ̃ŋ]", meaning: "joke" }, 
    { id: "nF002", type: "n", word: "Farcen", ipa: "[ˈfɒˑ.tɕɲ̩]", meaning: "pig" }, 
    { id: "nF003", type: "n", word: "Fåder", ipa: "[ˈfɒ.ɖɘ]", meaning: "father" }, 
    { id: "nF004", type: "n", word: "Finjer", ipa: "[ˈfɪ̃.ɲɘ]", meaning: "finger, digit" }, 
    { id: "nF005", type: "n", word: "Fisj", ipa: "[ˈfɪɕ]", meaning: "fish" }, 
    { id: "nF006", type: "n", word: "Frubrigh", ipa: "[ˈfɻ̥ʏ.bɻɪj]", meaning: "volcano" }, 
    { id: "nF007", type: "n", word: "Frubriglas", ipa: "[ˈfɻ̥ʏ.bɻɪˌɔɐs]", meaning: "volcano glass, dark glass, obsidian glass" }, 
    { id: "nF008", type: "n", word: "Fjanis", ipa: "[ˈfjɐ̃.nis]", meaning: "jail, prison" }, 
    { id: "nF009", type: "n", word: "Fjůln", ipa: "[ˈfjɯɔn]", meaning: "feeling" }, 
    { id: "nF010", type: "n", word: "Fjůr", ipa: "[ˈfjɯɘ]", meaning: "fire" }, 
    { id: "nF011", type: "n", word: "Foil", ipa: "[ˈfɔɪʎ]", meaning: "bird" }, 
    { id: "nF012", type: "n", word: "Fgrål", ipa: "[ˈfɹ̥ˠʷɒɔ]", meaning: "story" }, 
    { id: "nF013", type: "n", word: "fgrålcen", ipa: "[ˈfɹ̥ˠʷɒʎ.tɕɲ̩]", meaning: "small talk" }, 
    { id: "nF014", type: "n", word: "Fro", ipa: "[ˈfɻ̥oʊ]", meaning: "woman" }, 
    { id: "nF015", type: "n", word: "Frooc", ipa: "[ˈfɻ̥oʊtɕ]", meaning: "girl" }, 
    { id: "nF016", type: "n", word: "Frught", ipa: "[ˈfɻ̥ʏɥʔ]", meaning: "fruit" }, 
    { id: "nF017", type: "n", word: "Fůt", ipa: "[ˈfɯʔ]", meaning: "foot" }, 
    { id: "nF018", type: "n", word: "Fůtganjer", ipa: "[ˈfɯʔˌɰɐ̃.ɲɘ]", meaning: "pedestrian" }, 
    { id: "nF019", type: "n", word: "Fyl", ipa: "[ˈfaɔ]", meaning: "skin" }, 
    { id: "nF020", type: "n", word: "Fylighyd", ipa: "[ˈfa.lɪ.jaaʔ]", meaning: "safety" }, 
	 
    { id: "nG001", type: "n", word: "Glimlagh", ipa: "[ˈɔ̃ɪ̃m.lɐɘ]", meaning: "happiness" }, 
    { id: "nG002", type: "n", word: "God", ipa: "[ˈɰɔʔ]", meaning: "god" }, 
    { id: "nG003", type: "n", word: "Glas", ipa: "[ˈɔɐs]", meaning: "glass" }, 
    { id: "nG004", type: "n", word: "Gras", ipa: "[ˈɹʷˠɐs]", meaning: "grass" }, 
 
    { id: "nH001", type: "n", word: "Hand", ipa: "[ˈɦɒ̤̃ˑʔ]", meaning: "hand" }, 
    { id: "nH002", type: "n", word: "Håfin", ipa: "[ˈɦɒ̤.vɪ̃ɲ]", meaning: "harbour" }, 
    { id: "nH003", type: "n", word: "Heem", ipa: "[ˈɦẽ̤ɪ̤̃m]", meaning: "home" }, 
    { id: "nH004", type: "n", word: "Hjoorsåmhyd", ipa: "[ˈʝ̤o̤ʊ̤.ʂɒ̃m.ɦa̤ʔ]", meaning: "obedience" }, 
    { id: "nH005", type: "n", word: "Hjůs", ipa: "[ˈʝ̤ɯ̤s]", meaning: "house" }, 
    { id: "nH006", type: "n", word: "Hjůsnooi", ipa: "[ˈʝ̤ɯ̤zˌnɔʏɥ]", meaning: "window" }, 
    { id: "nH007", type: "n", word: "Hond", ipa: "[ˈɦõ̤ʊ̤̃ʔ]", meaning: "dog" }, 
    { id: "nH008", type: "n", word: "Hooft", ipa: "[ˈɦo̤ʊ̤f(t)]", meaning: "head" }, 
    { id: "nH009", type: "n", word: "Hors", ipa: "[ˈɦɔ̤ʂ]", meaning: "horse" }, 
    { id: "nH010", type: "n", word: "Hyrt", ipa: "[ˈɦa̤ɘ̤ʔ]", meaning: "heart" }, 
 
    { id: "nJ001", type: "n", word: "Jår", ipa: "[ˈjɒɘ]", meaning: "year" }, 
    { id: "nJ002", type: "n", word: "juldjen", ipa: "[ˈjʏʎ.dʑɲ̩]", meaning: "guilder" }, 
    { id: "nJ003", type: "n", word: "Jůr", ipa: "[ˈjɯɘ]", meaning: "hour" }, 
    { id: "nJ004", type: "n", word: "Jyld", ipa: "[ˈjaɔʔ]", meaning: "money" }, 
 
    { id: "nL001", type: "n", word: "Lefen", ipa: "[ˈleɪ.vɱ]", meaning: "life" }, 
    { id: "nL002", type: "n", word: "Letter", ipa: "[ˈlɛ.ʈɘ]", meaning: "letter" }, 
    { id: "nL003", type: "n", word: "Ljuck", ipa: "[ˈʎʏk]", meaning: "luck" }, 
    { id: "nL004", type: "n", word: "Lust", ipa: "[ˈlʏs(t)]", meaning: "desire, urge" }, 
 
    { id: "nM001", type: "n", word: "Man", ipa: "[ˈmɐ̃ŋ]", meaning: "man" }, 
    { id: "nM002", type: "n", word: "Manc", ipa: "[ˈmɒ̃ˑtɕ]", meaning: "boy" }, 
    { id: "nM003", type: "n", word: "Mand", ipa: "[ˈmɒ̃ˑʔ]", meaning: "month, season" }, 
    { id: "nM004", type: "n", word: "Masjimum", ipa: "[ˈmɐ.zɪ̃.mʏ̃m]", meaning: "maximum" }, 
    { id: "nM005", type: "n", word: "Menc", ipa: "[ˈmẽɪ̃tɕ]", meaning: "person" }, 
    { id: "nM006", type: "n", word: "Mind", ipa: "[ˈmɪ̃ˑʔ]", meaning: "middle, centre" }, 
    { id: "nM007", type: "n", word: "Minimum", ipa: "[ˈmɪ̃.nɪ̃.mʏ̃m]", meaning: "minimum" }, 
    { id: "nM008", type: "n", word: "Misnemin", ipa: "[ˈmɪsˌnẽɪ̃.mɪ̃ɲ]", meaning: "mistake" }, 
    { id: "nM009", type: "n", word: "Mjůs", ipa: "[ˈmjɯs]", meaning: "mouse" }, 
    { id: "nM010", type: "n", word: "Můder", ipa: "[ˈmɯ.ɖɘ]", meaning: "mother" }, 
 
    { id: "nN001", type: "n", word: "Naght", ipa: "[ˈnɐɘʔ]", meaning: "night" }, 
    { id: "nN002", type: "n", word: "Nakjůr", ipa: "[ˈnɐ.tɕɯɘ]", meaning: "nature" }, 
    { id: "nN003", type: "n", word: "Neus", ipa: "[ˈnɛʊs]", meaning: "nose" }, 
    { id: "nN004", type: "n", word: "Njietin", ipa: "[ˈɲi.tɪ̃ɲ]", meaning: "fun" }, 
    { id: "nN005", type: "n", word: "Njietplyc", ipa: "[ˈɲiʔˌplatɕ]", meaning: "third place, area away from work and family" }, 
    { id: "nN006", type: "n", word: "Njůt", ipa: "[ˈɲɯʔ]", meaning: "minute" }, 
    { id: "nN007", type: "n", word: "Nåm", ipa: "[ˈnɒ̃m]", meaning: "name" }, 
 
    { id: "nO001", type: "n", word: "Oghend", ipa: "[ˈʔoʊ.n̩ʔ]", meaning: "morning" }, 
    { id: "nO002", type: "n", word: "Onnergůd", ipa: "[ˈʔɔ̃.ɳɘ.wɯʔ]", meaning: "underwear" }, 
    { id: "nO003", type: "n", word: "Ooi", ipa: "[ˈʔɔʏɥ]", meaning: "eye" }, 
 
    { id: "nP001", type: "n", word: "Pård", ipa: "[ˈpʰɒɘʔ]", meaning: "vehicle" }, 
    { id: "nP002", type: "n", word: "Plyc", ipa: "[pʰl̥atɕ]", meaning: "place, spot" }, 
    { id: "nP003", type: "n", word: "Prerstir", ipa: "[ˈpɻ̥ɛ.ʂʈɪɘ]", meaning: "performance" }, 
    { id: "nP004", type: "n", word: "Prsoonlighyd", ipa: "[ˈpʂõʊ̃n.lɪ.jaʔ]", meaning: "personality" }, 
 
    { id: "nR001", type: "n", word: "Rodwyn", ipa: "[ˈɻɔʔˌvãŋ]", meaning: "red wine" }, 
    { id: "nR002", type: "n", word: "Rui", ipa: "[ˈɻʏɪ]", meaning: "back" }, 
    { id: "nR003", type: "n", word: "Ryght", ipa: "[ˈɻaɪʔ]", meaning: "right" }, 
 
    { id: "nS001", type: "n", word: "Se", ipa: "[ˈseɪ]", meaning: "sea" }, 
    { id: "nS002", type: "n", word: "Suåret", ipa: "[sʏɒˈɻɛʔ]", meaning: "cigarette" }, 
    { id: "nS003", type: "n", word: "Sjenck", ipa: "[ˈɕẽɪ̃k]", meaning: "gift" }, 
    { id: "nS004", type: "n", word: "Sjip", ipa: "[ˈɕɪp]", meaning: "ship" }, 
    { id: "nS005", type: "n", word: "Sjol", ipa: "[ˈɕoʊ]", meaning: "school" }, 
    { id: "nS006", type: "n", word: "Sjlaght", ipa: "[ɕʎ̥ɐɘʔ]", meaning: "gender" }, 
    { id: "nS007", type: "n", word: "Sjyrm", ipa: "[ˈɕaɘm]", meaning: "screen, protection" }, 
    { id: "nS008", type: "n", word: "Sleutel", ipa: "[ˈsl̥ɛʊ.ʔɔ]", meaning: "key" }, 
    { id: "nS009", type: "n", word: "Sorgh", ipa: "[ˈsɔ.ɻoʊ]", meaning: "care, worry" }, 
    { id: "nS010", type: "n", word: "Stuck", ipa: "[ˈstʏk]", meaning: "piece" }, 
    { id: "nS011", type: "n", word: "Stylin", ipa: "[ˈsta.lɪɲ]", meaning: "system" }, 
 
    { id: "nT001", type: "n", word: "Tål", ipa: "[ˈtʰɒɔ]", meaning: "language" }, 
    { id: "nT002", type: "n", word: "Tålscund", ipa: "[ˈtʰɒɔs.tɕʏ̃ˑʔ]", meaning: "linguistics" }, 
    { id: "nT003", type: "n", word: "Tand", ipa: "[ˈtʰɒ̃ˑʔ]", meaning: "tooth" }, 
    { id: "nT004", type: "n", word: "Ton", ipa: "[ˈtʰɔ̃ŋ]", meaning: "tongue" }, 
    { id: "nT005", type: "n", word: "Tryck", ipa: "[ˈʈʂɻak]", meaning: "journey, visit" }, 
    { id: "nT006", type: "n", word: "Tyd", ipa: "[tʰaʔ]", meaning: "time" }, 
 
    { id: "nU001", type: "n", word: "Unifyrste", ipa: "[ʔʏ.nɪˈvaˌʂʈeɪ]", meaning: "university" }, 
    { id: "nU002", type: "n", word: "Uinblick", ipa: "[ˈʔʏ̃ɪ̃ɲ.blɪk]", meaning: "moment" }, 
 
    { id: "nŮ001", type: "n", word: "Ůf", ipa: "[ˈʔɯf]", meaning: "practice" }, 
 
    { id: "nW001", type: "n", word: "Wåter", ipa: "[ˈvɒ.ʔɘ]", meaning: "water" }, 
    { id: "nW002", type: "n", word: "Wesen", ipa: "[ˈveɪ.zn̩]", meaning: "being" }, 
    { id: "nW003", type: "n", word: "Word", ipa: "[ˈvɔɘʔ]", meaning: "word" }, 
    { id: "nW004", type: "n", word: "Wygh", ipa: "[ˈvaɪ]", meaning: "way, manner, path, away" }, 
    { id: "nW005", type: "n", word: "Wyn", ipa: "[ˈvãŋ]", meaning: "wine" }, 
    { id: "nW006", type: "n", word: "Vyrld", ipa: "[ˈvaɭʔ]", meaning: "world" }, 
    { id: "nW007", type: "n", word: "Woordenbůck", ipa: "[ˈvoʊ.ɖɳˌbɯk]", meaning: "dictionary, wordbook" }, 
 
    { id: "nY001", type: "n", word: "Yngel", ipa: "[ˈʔa.ŋɔ]", meaning: "angel, loved one" }, 
    { id: "nY002", type: "n", word: "Ys", ipa: "[ˈʔas]", meaning: "ice" }, 
   
    { id: "nÅ003", type: "n", word: "Åp", ipa: "[ˈʔɒp]", meaning: "ape" }, 
    { id: "nÅ004", type: "n", word: "Åpsj", ipa: "[ˈʔɒpɕ]", meaning: "monkey" }, 
    { id: "nC010", type: "n", word: "Cåbjůs", ipa: "[ˈkʰɒ.bjɯs]", meaning: "kitchen" }, 
    { id: "nE003", type: "n", word: "Ecoorn", ipa: "[ˈʔeɪ.kʰõʊ̃ɳ]", meaning: "squirrel" }, 
    { id: "nI001", type: "n", word: "Indruck", ipa: "[ˈʔɪ̃ɳ.ɖʐɻʏk]", meaning: "pressue" }, 
    { id: "nJ005", type: "n", word: "Jyt", ipa: "[ˈjaʔ]", meaning: "goat" }, 
    { id: "nN008", type: "n", word: "Nåjel", ipa: "[ˈnɒ.jɔ]", meaning: "nail" }, 
    { id: "nO004", type: "n", word: "Ordin", ipa: "[ˈʔɔ.ɖɪ̃ɲ]", meaning: "order" }, 
    { id: "nO005", type: "n", word: "Oorsåck", ipa: "[ˈʔoʊˌʐɒk]", meaning: "cause" }, 
    { id: "nQ001", type: "n", word: "Quast", ipa: "[ˈkfɐs(t)]", meaning: "brush" }, 
    { id: "nD005", type: "n", word: "Disj", ipa: "[ˈdɪɕ]", meaning: "table" }, 
    { id: "nS012", type: "n", word: "Sjů", ipa: "[ˈɕɯ]", meaning: "shoe" }, 
    { id: "nF021", type: "n", word: "Forstylin", ipa: "[ˈfɔˌʂʈa.lɪ̃ɲ]", meaning: "idea" }, 
    { id: "nA003", type: "n", word: "Aripennon", ipa: "[ʔɐ.ɻɪˈpʰɛ̃.nɔ̃ŋ]", meaning: "extremity" }, 
    { id: "nK001", type: "n", word: "Kjost", ipa: "[ˈtɕɔs(t)]", meaning: "cost" }, 
    { id: "nF022", type: "n", word: "Fjårdagh", ipa: "[ˈfjɒɘˌdɐɘ]", meaning: "birthday" }, 

    { id: "vA001", type: "v", word: "acepten", ipa: "[ʔɐˈtɕɛp.ʔn̩]", meaning: "accept" }, 
    { id: "vÅ001", type: "v", word: "ånfården", ipa: "[ˈʔɒ̃ɱ.fɒ.ɖɳ̩]", meaning: "address" }, 
    { id: "vB001", type: "v", word: "bhoden", ipa: "[ˈbɦo̤ʊ̤.dn̩]", meaning: "preserve, save" }, 
    { id: "vC001", type: "v", word: "cacen", ipa: "[ˈkʰɐ.tɕɲ̩]", meaning: "poop" }, 
    { id: "vC002", type: "v", word: "cacken", ipa: "[ˈkʰɐ.ʔŋ̩]", meaning: "shit" }, 
    { id: "vC003", type: "v", word: "comen", ipa: "[ˈkʰõʊ̃.mŋ̩]", meaning: "come" }, 
    { id: "vD001", type: "v", word: "dencen", ipa: "[ˈdɛ̃ɲ.tɕɲ̩]", meaning: "think" }, 
    { id: "vF001", type: "v", word: "fůln", ipa: "[ˈfɯɔn]", meaning: "feel" }, 
    { id: "vG001", type: "v", word: "gån", ipa: "[ˈɰɒ̃ŋ]", meaning: "go" }, 
    { id: "vG002", type: "v", word: "gråln", ipa: "[ˈɹʷˠɒɔn]", meaning: "repeat" }, 
    { id: "vH001", type: "v", word: "hebben", ipa: "[ˈɦɛ̤.bm̩]", meaning: "have" }, 
    { id: "vH002", type: "v", word: "hoorn", ipa: "[ˈɦõ̤ʊ̤̃ɳ]", meaning: "hear" }, 
    { id: "vM001", type: "v", word: "moin", ipa: "[ˈmɔɪ̃ɲ]", meaning: "may, be allowed" }, 
    { id: "vS001", type: "v", word: "syn", ipa: "[ˈsãŋ]", meaning: "be" }, 
    { id: "vB002", type: "v", word: "bhoorn", ipa: "[ˈbɦõ̤ʊ̤̃ɳ]", meaning: "belong" }, 
    { id: "vB003", type: "v", word: "boon", ipa: "[ˈbõʊ̃ŋ]", meaning: "build" },  
    { id: "vM002", type: "v", word: "můten", ipa: "[ˈmɯ.tɕɲ̩]", meaning: "have to, must" },  
    { id: "vS002", type: "v", word: "suln", ipa: "[ˈsʏɔn]", meaning: "shall" }, 
    { id: "vW001", type: "v", word: "wyrcen", ipa: "[ˈvaɻ.tɕɲ̩]", meaning: "work" }, 
    { id: "vS003", type: "v", word: "seen", ipa: "[ˈsẽɪ̃ɲ]", meaning: "say" }, 
    { id: "vC004", type: "v", word: "cennen", ipa: "[ˈtɕɛ̃.nŋ̩]", meaning: "know" }, 
    { id: "vD002", type: "v", word: "drincen", ipa: "[ˈɖʐɻɪ̃ɲ.tɕɲ̩]", meaning: "drink" }, 
    { id: "vO001", type: "v", word: "oplycen", ipa: "[ˈʔɔpˌla.tɕɲ̩]", meaning: "look like" }, 
    { id: "vL001", type: "v", word: "lycen", ipa: "[ˈla.tɕɲ̩]", meaning: "seem" }, 
    { id: "vE001", type: "v", word: "eten", ipa: "[ˈʔeɪ.ʔn̩]", meaning: "eat" }, 
    { id: "vJ001", type: "v", word: "jissen", ipa: "[ˈjɪ.zn̩]", meaning: "guess" }, 
    { id: "vL002", type: "v", word: "lesen", ipa: "[ˈleɪ.zn̩]", meaning: "learn, read, gather information for a specific event or reason" }, 
    { id: "vS004", type: "v", word: "sůcen", ipa: "[ˈsɯ.tɕɲ̩]", meaning: "search, seek, look for" }, 
    { id: "vB004", type: "v", word: "bsůcen", ipa: "[ˈbzɯ.tɕɲ̩]", meaning: "visit" }, 
    { id: "vS005", type: "v", word: "sjjůrn", ipa: "[ˈɕjɯ̃ɳ]", meaning: "tidy up, assemble" }, 
    { id: "vM003", type: "v", word: "måcen", ipa: "[ˈmɒ.tɕɲ̩]", meaning: "make" }, 
    { id:"vH003", word:"hetensa", ipa:"[ˈɦe̤ɪ̤.ʔn̩ˌsɐ]", meaning:"be called", type:"v" }, 
    { id: "vH004", type: "v", word: "heten", ipa: "[ˈɦe̤ɪ̤.ʔn̩]", meaning: "call, phone" }, 
	{ id: "vW002", type: "v", word: "wyrden", ipa: "[ˈva.ɖɳ̩]", meaning: "become, occur" },
	{ id: "vW003", type: "v", word: "weten", ipa: "[ˈveɪ.ʔn̩]", meaning: "know" },
	{ id: "vL003", type: "v", word: "leghn", ipa: "[ˈlẽɪ̃ɲ]", meaning: "lay, put lying down" },
	{ id: "vL004", type: "v", word: "lighn", ipa: "[ˈlɪ̃j̃ɲ]", meaning: "lie, be lying down, be located lying down" },
	{ id: "vB005", type: "v", word: "boofstån", ipa: "[ˈboʊfˌstɒ̃ŋ]", meaning: "stand up, be standing up" },
	{ id: "vO002", type: "v", word: "opstån", ipa: "[ˈʔɔpˌstɒ̃ŋ]", meaning: "place standing up" },
	{ id: "vS006", type: "v", word: "stån", ipa: "[ˈstɒ̃ŋ]", meaning: "be standing, be located standing" },
	{ id: "vS007", type: "v", word: "setten", ipa: "[ˈsɛ.ʔn̩]", meaning: "place sitting, set, put" },
	{ id: "vS008", type: "v", word: "sitten", ipa: "[ˈsɪ.ʔn̩]", meaning: "sit, be located sitting" },
	{ id: "vC005", type: "v", word: "cunnen", ipa: "[ˈtɕʏ̃.nŋ̩]", meaning: "be able" },

    { id: "aA001", type: "a", word: "Anmoinligh", ipa: "[ʔɐ̃ŋˈmɔ̃ɪ̃ɲ.ʎɪj]", meaning: "impossible" }, 
    { id: "aA002", type: "a", word: "Anryght", ipa: "[ʔɐ̃ɳˈɻaɪʔ]", meaning: "incorrect, wrong" }, 
    { id: "aB001", type: "a", word: "Bloshandåfigh", ipa: "[ˈblɔsˌɦɐ̤̃n.dɒ.fɪj]", meaning: "cute" }, 
    { id: "aQ001", type: "a", word: "Quick", ipa: "[kfɪk]", meaning: "smart" }, 
    { id: "aC001", type: "a", word: "Clyn", ipa: "[ˈkl̥ãŋ]", meaning: "small" }, 
 
]; 